[project]
name = "Curso-FastAPI"
version = "0.1.0"
description = "Realizando o curso do Eduardo Mendes de FastAPI-2025, para terminar o projeto que o Pedro me deu, migrar o projeto de django para FastAPI."
readme = "README.md"
authors = [
    { name = "maycon-persch", email = "mayconpersch01@gmail.com"} ,
    {  name = "Pedro", email = " ? "}
    
]
requires-python = ">=3.14"

dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "harlequin>=2.15.0",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.14.0",
    "sqlalchemy[asyncio]>=2.0.54",
]

[project.scripts]
curso-fastapi = "main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
    "freezegun>=1.5.5",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.8",
]

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ["I", "F", "E", "W", "PL", "PT", "FAST"]


[tool.ruff.format]
preview = true
quote-style = "double"

[tool.uv]
package = false
