"""modificações

Revision ID: f63b747aec59
Revises: 104d8b9ba859
Create Date: 2026-09-28 10:31:45.788672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63b747aec59'
down_revision: Union[str, Sequence[str], None] = '104d8b9ba859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'id_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_admin', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
